
#include <stdint.h>
#include "gpio.h"

#ifndef NB_CONFIG_H
#define NB_CONFIG_H

#define NBEVENT_BTHSERIAL_DMA_TRANSFER_OVER 0x80

static uint32_t SYSLED_INTERVAL=1000;

#define NBPIN_VIBRATORL_PORT GPIOA
#define NBPIN_VIBRATORR_PORT GPIOA

#define NBPIN_VIBRATORL_PIN VibratorL_Pin
#define NBPIN_VIBRATORR_PIN VibratorR_Pin

#define NBACT_VIBRATORL_ENABLE HAL_GPIO_WritePin(NBPIN_VIBRATORL_PORT,NBPIN_VIBRATORL_PIN, GPIO_PIN_SET);

#define NBACT_VIBRATORL_DISABLE HAL_GPIO_WritePin(NBPIN_VIBRATORL_PORT,NBPIN_VIBRATORL_PIN, GPIO_PIN_RESET);

#define NBACT_VIBRATORR_ENABLE HAL_GPIO_WritePin(NBPIN_VIBRATORR_PORT,NBPIN_VIBRATORR_PIN, GPIO_PIN_SET);

#define NBACT_VIBRATORR_DISABLE HAL_GPIO_WritePin(NBPIN_VIBRATORR_PORT,NBPIN_VIBRATORR_PIN, GPIO_PIN_RESET);





#endif

